import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react'
import Link from 'next/link'

export default function Home() {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="" />
      </Head>
      <main className={styles.main}>
        <video
          preload="auto"
          playsInline
          autoPlay
          muted
          loop>
          <source src="/Tutorial-BG.mp4" type="video/mp4" />
        </video>
        <Link href = "/quiz">Quiz</Link>
      </main>
    </>
  )
}
